# Generated by Django 4.0.5 on 2022-06-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Designations', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('Facebook', models.URLField(max_length=100)),
                ('Google', models.URLField(max_length=100)),
                ('Twitter', models.URLField(max_length=100)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
